name: Coinbase Spot Price
description: Chainlink external adapter to retrieve Coinbase spot price
node_identifier: coinbase-spot-price
platforms:
  - Cloudflare Workers (https://workers.cloudflare.com/)
data_sources:
  - name: Coinbase
    url: https://api.coinbase.com/v2/prices/
parameters:
  - pair
